name: PHP Quality Assurance

on:
  push:
    branches:
      - "**"   
  pull_request:
    branches:
      - "**"  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: dist-${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            dist-${{ runner.os }}-php-


      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Linter
        run: composer lint

      - name: Run Static Analysis
        run: composer analyse

      - name: Run tests
        run: composer test

      - name: Fix permissions on phpunit
        run: chmod +x vendor/bin/phpunit 

      - name: Generate HTML Coverage Report
        run: vendor/bin/phpunit --coverage-html build/coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report   
          path: build/coverage/

  deploy:
    needs: build  
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deployment
        run: |
          echo "==================================="
          echo " Déploiement en production..."
          echo "Connexion au serveur..."
          sleep 2
          echo "Pull du code..."
          sleep 2
          echo "Migration de la base..."
          sleep 2
          echo " Déploiement terminé avec succès !"
          echo "==================================="
